sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vikramtanwar/testreact -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vikramtanwar/testreact npm run test -- --coverage

after_success:
  - docker build -t vikramtanwar/multiclient ./client
  - docker build -t vikramtanwar/multinginx ./nginx
  - docker build -t vikramtanwar/multiserver ./server
  - docker build -t vikramtanwar/multiworker ./worker
#Log in to Docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
#Take the images and push to docker hub
  - docker push vikramtanwar/multiclient
  - docker push vikramtanwar/multinginx
  - docker push vikramtanwar/multiserver
  - docker push vikramtanwar/multiworker
