sudo: required
services:
  - docker

before_install:
  - docker build -t testreact -f ./client/Dockerfile.dev .

script:
  - docker run testreact npm run test -- --coverage

after_success:
  - docker build -t thevee/multiclient ./client
  - docker build -t thevee/multinginx ./nginx
  - docker build -t thevee/multiserver ./server
  - docker build -t thevee/multiworker ./worker

#Log in to Docker CLI
 

#Take the images and push to docker hub
